"""
This module contains the base class for all callback handlers.
"""

from abc import ABC, abstractmethod
from pydantic import BaseModel, Field


class SenderInfo(BaseModel):
    """
    Contains information about the sender of the message.
    """
    name:str = Field(description="The name of the sender.")
    role:str = Field(description="The role of the sender.")


class BaseCallbackHandler(ABC):
    """
    Base class for all callback handlers.
    """

    @abstractmethod
    def on_new_message(self, sender_info:SenderInfo)->None:
        """
        Called when a new message is received.
        Args:
            sender_info: Sender Info object containing sender info
        """

    @abstractmethod
    def on_new_token_generated(self, token:str)->None:
        """
        Called when a new token is generated.
        Args:
            token: The token generated by the LLM Model
        """

    @abstractmethod
    def on_new_workspace_generated(self, workspace_path:str)->None:
        """
        Called when a new workspace is generated.
        Args:
            workspace_path: The path to the generated workspace
        """

    @abstractmethod
    def on_cost_updated(self, cost:float)->None:
        """
        Called when the cost is updated.
        Args:
            cost: The cost of the current message
        """

    
    @abstractmethod
    def on_new_file_generated(self, sender_info:SenderInfo, file_type:str, file_path:str)->None:
        """
        Called when a new file is generated.
        Args:
            sender_info: Sender Info object containing sender info
            file_type: The type of the generated file
            file_path: The path to the generated file
        """

    def on_message_end(self)->None:
        """
        Called when the message ends.
        """
